### ISSUE TITLE
KeyError: 'TransformerTransferPredictor'

### ISSUE THREAD

**Issue by zhanwenchen** [ZhuGeKongKong/SGG-G2S#2]
Sorry I can't figure this one out after fixing the last issue. Can you please take a look?

```
2022-02-14 20:08:56,786 maskrcnn_benchmark INFO: Saving config into: ./checkpoints/transformer_predcls_dist15_3k_FixPModel_lr1e3_B16_FCMat/config.yml
2022-02-14 20:08:56,796 maskrcnn_benchmark INFO: #################### prepare training ####################
Traceback (most recent call last):
  File "tools/relation_train_net.py", line 446, in <module>
    main()
  File "tools/relation_train_net.py", line 439, in main
    model = train(cfg, args.local_rank, args.distributed, logger)
  File "tools/relation_train_net.py", line 55, in train
    model = build_detection_model(cfg) 
  File "/home/zhanwen/sgb/sgb/maskrcnn_benchmark/modeling/detector/detectors.py", line 10, in build_detection_model
    return meta_arch(cfg)
  File "/home/zhanwen/sgb/sgb/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 31, in __init__
    self.roi_heads = build_roi_heads(cfg, self.backbone.out_channels)
  File "/home/zhanwen/sgb/sgb/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 89, in build_roi_heads
    roi_heads.append(("relation", build_roi_relation_head(cfg, in_channels)))
  File "/home/zhanwen/sgb/sgb/maskrcnn_benchmark/modeling/roi_heads/relation_head/relation_head.py", line 105, in build_roi_relation_head
    return ROIRelationHead(cfg, in_channels)
  File "/home/zhanwen/sgb/sgb/maskrcnn_benchmark/modeling/roi_heads/relation_head/relation_head.py", line 33, in __init__
    self.predictor = make_roi_relation_predictor(cfg, feat_dim)
  File "/home/zhanwen/sgb/sgb/maskrcnn_benchmark/modeling/roi_heads/relation_head/roi_relation_predictors.py", line 689, in make_roi_relation_predictor
    func = registry.ROI_RELATION_PREDICTOR[cfg.MODEL.ROI_RELATION_HEAD.PREDICTOR]
KeyError: 'TransformerTransferPredictor'
Killing subprocess 4536
Traceback (most recent call last):
  File "/home/zhanwen/anaconda3/envs/sgb/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhanwen/anaconda3/envs/sgb/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zhanwen/anaconda3/envs/sgb/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/zhanwen/anaconda3/envs/sgb/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/zhanwen/anaconda3/envs/sgb/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zhanwen/anaconda3/envs/sgb/bin/python', '-u', 'tools/relation_train_net.py', '--local_rank=0', '--config-file', 'configs/e2e_relation_X_101_32_8_FPN_1x_transformer.yaml', 'MODEL.ROI_RELATION_HEAD.USE_GT_BOX', 'True', 'MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL', 'True', 'MODEL.ROI_RELATION_HEAD.PREDICTOR', 'TransformerTransferPredictor', 'MODEL.ROI_RELATION_HEAD.PREDICT_USE_BIAS', 'True', 'DTYPE', 'float32', 'SOLVER.IMS_PER_BATCH', '16', 'TEST.IMS_PER_BATCH', '1', 'SOLVER.MAX_ITER', '16000', 'SOLVER.BASE_LR', '1e-3', 'SOLVER.SCHEDULE.TYPE', 'WarmupMultiStepLR', 'SOLVER.STEPS', '(10000, 16000)', 'SOLVER.VAL_PERIOD', '3000', 'SOLVER.CHECKPOINT_PERIOD', '2000', 'GLOVE_DIR', './datasets/vg/', 'MODEL.PRETRAINED_DETECTOR_CKPT', './checkpoints/pretrained_faster_rcnn/model_final.pth', 'OUTPUT_DIR', './checkpoints/transformer_predcls_dist15_3k_FixPModel_lr1e3_B16_FCMat']' returned non-zero exit status 1.
```

**Comment by ZhuGeKongKong** [comment]
Please check whether there is the TransformerTransferPredictor class in your  modeling/roi_heads/relation_head/roi_relation_predictors.py. 
as mentioned in Line276 of https://github.com/ZhuGeKongKong/SGG-G2S/blob/main/maskrcnn_benchmark/modeling/roi_heads/relation_head/roi_relation_predictors.py

**Comment by zhanwenchen** [comment]
Thanks @ZhuGeKongKong. The problem was that I provided the incorrect code paths to the config files so that they pointed to the KaihuaTang `maskrcnn_benchmark` code instead of the `maskrcnn_benchmark` in this library, which is completely different.
